sockets = ["0.0.0.0:8080"]
auth_public_key = "/opt/confidential-containers/kbs/user-keys/public.pub"
insecure_http = true

[plugin_manager_config]
work_dir = "/opt/confidential-containers/kbs/plugin"
enabled_plugins = []

[attestation_token_config]
attestation_token_type = "CoCo"

[grpc_config]
as_addr = "http://as:50004"
